#!/usr/bin/python
import cgi
import cgitb
import os
from os.path import expanduser
import subprocess

cgitb.enable()
form = cgi.FieldStorage()
for k in form.keys():
  if k == 'pythonCode':
    home = expanduser("~")
    filePath = home+'/pythonCode.py' 
    f = open(filePath,'w')
    #for i in form:
    f.write(form["pythonCode"].value)
    f.close()

proc = subprocess.Popen(['pgrep','-f','monitor.py'],stdout=subprocess.PIPE)
proc.wait()
proc = subprocess.Popen(['kill',proc.stdout.read().rstrip('\n')])
proc.wait()

os.system("python /www/cgi-bin/monitor.py&")

print "Content-Type: text/html"
print "Location: /blockly/demos/code/"
print
print '<html>'
print '  <head>'
print '    <meta http-equiv="refresh" content="0;url=/blockly/demos/code/" />'
print '    <title>You are going to be redirected</title>'
print '  </head>' 
print '  <body>'
print '    Redirecting... <a href="/blockly/demos/code/">Click here if you are not redirected</a>'
print '  </body>'
print '</html>'

