#! /usr/bin/python

# This code receive from Code.post()

import cgi
import cgitb
import os
from os.path import expanduser
import subprocess

cgitb.enable()

print "Content-type: text/plain"
print

print "debug"
f = cgi.FieldStorage()
print f
for k in f.keys():
  if k == 'pythonCode':
    home = expanduser("~")
    filePath = home+'/pythonCode.py' 
    fo = open(filePath,'w')
    #for i in form:
    fo.write(f.getfirst(k))
  elif k == "key" and f.getfirst(k) == "stop":
    os.system("kill `pgrep -f pythonCode`")
  fo.close()

proc = subprocess.Popen(['pgrep','-f','monitor.py'],stdout=subprocess.PIPE)
proc.wait()
proc = subprocess.Popen(['kill',proc.stdout.read().rstrip('\n')])
proc.wait()

os.system("python /www/cgi-bin/monitor.py&")


