#!/usr/bin/python
import cgi
import cgitb
import os

cgitb.enable()
form = cgi.FieldStorage()
f = open('/root/pythonCode.py','w')
#for i in form:
f.write(form["pythonCode"].value)
f.close()

if not os.path.isdir("/sys/class/gpio/gpio3"):
  os.system("echo 3 > /sys/class/gpio/export")
os.system("echo 'out' > /sys/class/gpio/gpio3/direction")
os.system("echo 0 > /sys/class/gpio/gpio3/value")
os.system("echo 1 > /sys/class/gpio/gpio3/value")
os.system("kill `pgrep -f pythonCode`")
os.system("python /root/pythonCode.py&")

print "Content-Type: text/html"
print "Location: /blockly/demos/code/"
print
print '<html>'
print '  <head>'
print '    <meta http-equiv="refresh" content="0;url=/blockly/demos/code/" />'
print '    <title>You are going to be redirected</title>'
print '  </head>' 
print '  <body>'
print '    Redirecting... <a href="/blockly/demos/code/">Click here if you are not redirected</a>'
print '  </body>'
print '</html>'
