#! /usr/bin/python

# This code receive from BlocklyStorage.link()

import cgi
import cgitb
import os



cgitb.enable()

print "Content-type: text/plain"
print

os.system("cp /www/save/last /www/save/last.old")
f = cgi.FieldStorage()

for k in f.keys():
    if k == 'xml':
        print "last"
        file = open('/www/save/last','w')
        file.write(f.getfirst(k))
        file.close()
    elif k == 'key' and f.getfirst(k) == 'last':
        with open('/www/save/last', 'r') as fin:
            print fin.read()

