#! /usr/bin/python

import cgi
import os
import cgitb
cgitb.enable()

print "Content-type: text/plain"
print

os.system("cp /var/www/save/last /var/www/save/last.old")
f = cgi.FieldStorage()

for k in f.keys():
    if k == 'xml':
        print "last"
        file = open('/var/www/save/last','w')
        file.write(f.getfirst(k))
        file.close()
    elif k == 'key' and f.getfirst(k) == 'last':
        with open('/var/www/save/last', 'r') as fin:
            print fin.read()


